language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: PyA4wpSgzRuf5bhJMHXTcufPKHEl8Ks4ZMCgOL23k+TfuLXKgM8tVmm4gXJLdOfoOVc5wvg00Eig3gL7w4Cipe2VbiWaagbYvQAMSaOMnTNKxjQfsaP+Na8J90PxCTh1/wjHtmDttUhitd1oNy3WosvEKaDoCH3VzMZ5lW4zaDNWiLn2oPK7f0pMIef/je5cPmhzZ9TzMyIv8N4FuKief3ONKH01WmZM+XmK+J9r1jb2Bt622TSSiLEIKXP62BBM5IWqDbY/7riUl+dHRig6CQ12c44BDoM3zMxLh3RNF5DzfWz/WvUoZ+0nmqZ+y8SaveJ2vqL/+Gq6HU6C7BDaeVnEsXAoX4VwB0vCpAUG4dF3i+rdphE2eKWezuCvdFyVsIClhNCqPEDdM/JpBuwjGw0U5AaSLT+Enfy6tAl5QAaqDSyzXGlEWajcz2LeGs+VRzbmf/fWdZuQaGLXiu9FmsTEAPOOhhrEyQ4HVznXm5mSZIgK3FaBTUMf8Wg4+YyVYAgX6dmVBPMyyNgiiKZjrps/8v65cLjioaRv6j5GlNMgcQYUMSl45VFAKAmULSsy8RuTMFKbnEpgNMxNx3qczwxTcbeAWdSVKcpoz/YTWe3pNF2dqZqN7RcbmrbkWm+JsCJTzLKe+SrIjUPZBxHrberteM0XCyuHDZb6SQrO2LI=
